---
title: "Projekt"
author: "Michał Kozioł"
format:
  html:
    theme: cosmo (HTML Theming – Quarto)
    toc: true
    toc-location: left
    toc-title: "Spis treści"
    toc-depth: 3
    number-sections: true
    smooth-scroll: true
---

# Wstęp

Powiązania między warunkami pogodowymi a ilością oraz jakością zbiorów tymianku.

Fajsławice to polskie zagłębie ziól, znajomość korelacji między pogodą a spodziewanymi zbiorami byłoby korzystne dla rolników i hurtowni.

Tymianek jest ziołem używanym do wielu rzeczy. Jego główną miarą jakości jest stężenie olejków eterycznych. Sadzi się go w okolicach kwietnia a zbiera od połowy września do października-listopada

# Pytania badawcze i hipotezy

**P1 Jak wilgotność w pogodzie wpływa na jakość i ilość tymianku?**

-   H1 Stan wody w najbliższej mierzonej rzece nie ma zauważalnego wpływu na uprawę tymianku
-   H2 Średnia wilgotność ma wpływ na wilgoć mierzoną w tymianku oraz na ilość olejków
-   H3 Opady w miesiącach zbiorów tymianku negatywnie wpływają na jego jakość
-   H4 Opady w miesiącach wzrostu tymianku pozytywnie wpływają na jego ilość

**P2 Jak sytuacja przy gruncie wpływa na jakość i ilość tymianku?**

-   H1 Minimalna temperatura gruntu w pierwszych miesiącach wzrostu tymianku ma wpływ na jego ilość w okresie zbiorów.
-   H2 Ilość dni z zaobserwowaną rosą w pierwszych miesiącach wzrostu tymianku ma wpływ na jego ilość w okresie zbiorów.

**P3 Jak warunki atmosferyczne wpływają na jakość i ilość tymianku?**

-   H1 Duże nasłonecznienie w miesiącach zbiorów tymianku pozytywnie wpływają na jego jakość.
-   H2 Duże nasłonecznienie w miesiącach sadzenia tymianku negatywnie wpływają na jego ilość podczas zbiorów.
-   H3 Ciśnienie atmosferyczne nie wpływa znacznie na uprawy tymianku.
-   H4 Prędkość wiatru nie wpływa znacznie na uprawy tymianku.

# Eksploracja zbioru danych

Dane pogodowe zostały zebrane z publicznych archiwów IMGW. Dane dotyczące zbiorów tymianku zostały podarowane przez firmę prowadzącą skup.

Szczegółowe dane zbiorów tymianku są zbierane dopiero od połowy 2019 roku.

Dane tymianku nie zawierają informacji kiedy tymianek został zebrany. Tymianek w magazynie może być aż do półtora roku.

Pewne szczegółowe dane pogodowe kończą się na początku 2024 roku, a te bardziej ogólne w połowie 2024.

Oznacza to, że analizowane będą dane z 4-5 lat. Dla danych rolniczych nie jest to duży zakres czasu, jednak nadal można wyciągać z niego wnioski.

```{r}
library(ggplot2)
library(dplyr)
library(tidyselect)
library(tidyverse)
library(lubridate)
library(stringr)

#####Przyjęcie i obróbka danych ogólnych

ZiolaOgol <- read.csv("D://Pulpit//Pogoda//ZiolaCalyOgol.csv")
ZiolaOgol$Data <- as.Date.character(ZiolaOgol$Data, tryFormats = c("%d.%m.%Y"))
ZiolaOgol$Kilo <- chartr(",", ".", ZiolaOgol$Kilo)
ZiolaOgol$Kilo <- as.numeric(ZiolaOgol$Kilo)
ZiolaOgol <- ZiolaOgol |>
  group_by(Data) |> 
  summarise(Kilo = sum(Kilo, na.rm=T))
ZiolaOgol <- ZiolaOgol |> 
  mutate(Rok = year(Data),
         Miesiac = month(Data),
         Dzien = day(Data))

######Przyjęcie i obróbka danych szczególnych

ZiolaSzczeg <- read.csv("D://Pulpit//Pogoda//ZiolaCalySzczegol.csv")
ZiolaSzczeg$Rok <- substr(ZiolaSzczeg$Kod, 2, 3)
ZiolaSzczeg$Miesiac <- substr(ZiolaSzczeg$Kod, 4, 5)
ZiolaSzczeg$Dzien <- substr(ZiolaSzczeg$Kod, 6, 7)
ZiolaSzczeg$Kod <- substr(ZiolaSzczeg$Kod, 2, 7)

ZiolaSzczeg$Waga <- chartr(",", ".", ZiolaSzczeg$Waga)
ZiolaSzczeg$Waga_Pz <- chartr(",", ".", ZiolaSzczeg$Waga_Pz)
ZiolaSzczeg$Wilg <- chartr(",", ".", ZiolaSzczeg$Wilg)
ZiolaSzczeg$Piach <- chartr(",", ".", ZiolaSzczeg$Piach)
ZiolaSzczeg$Olej <- chartr(",", ".", ZiolaSzczeg$Olej)

ZiolaSzczeg$Waga <- as.numeric(ZiolaSzczeg$Waga)
ZiolaSzczeg$Waga_Pz <- as.numeric(ZiolaSzczeg$Waga_Pz)
ZiolaSzczeg$Wilg <- as.numeric(ZiolaSzczeg$Wilg)
ZiolaSzczeg$Piach <- as.numeric(ZiolaSzczeg$Piach)
ZiolaSzczeg$Olej <- as.numeric(ZiolaSzczeg$Olej)
ZiolaSzczeg$Rok <- as.numeric(ZiolaSzczeg$Rok)
ZiolaSzczeg$Miesiac <- as.numeric(ZiolaSzczeg$Miesiac)
ZiolaSzczeg$Dzien <- as.numeric(ZiolaSzczeg$Dzien)

ZiolaSzczeg <- ZiolaSzczeg |>
  group_by(Kod) |> 
  summarise(Waga = sum(Waga, na.rm=T),
            Waga_Pz = sum(Waga_Pz, na.rm=T),
            Wilg = mean(Wilg, na.rm=T),
            Piach = mean(Piach, na.rm=T),
            Olej = mean(Olej, na.rm=T),
            Rok = mean(Rok, na.rm=T),
            Miesiac = mean(Miesiac, na.rm=T),
            Dzien = mean(Dzien, na.rm=T),
            DataKod = paste(Rok, str_pad(Miesiac, 2, pad = "0"), sep = "-"))
ZiolaSzczeg$DataKod <- paste0("20", ZiolaSzczeg$DataKod)

############Wypełnienie wartości 0 i null

SredWilg <- mean(ZiolaSzczeg$Wilg, na.rm = TRUE)
SredPiach <- mean(ZiolaSzczeg$Piach, na.rm = TRUE)
SredOlej <- mean(ZiolaSzczeg$Olej, na.rm = TRUE)

ZiolaSzczeg$Wilg[is.na(ZiolaSzczeg$Wilg)] <- SredWilg
ZiolaSzczeg$Piach[is.na(ZiolaSzczeg$Piach)] <- SredPiach
ZiolaSzczeg$Olej[is.na(ZiolaSzczeg$Olej)] <- SredOlej
ZiolaSzczeg$Waga_Pz[ZiolaSzczeg$Waga_Pz == 0] <- ZiolaSzczeg$Waga

###################

  ggplot(ZiolaSzczeg[ZiolaSzczeg$Rok == 20,], aes(x=Kod, y=Waga)) + 
  geom_bar(stat = "identity")

##################Ogarniecie danych rzekowych

Wieprz <- read.csv("D://Pulpit//Pogoda//Wieprz_Combo.csv")
Wieprz <- Wieprz %>%
  filter(Ekst == 2) %>%
  mutate(DataKod = paste(Rok, str_pad(Mies_Kalendarz, 2, pad = "0"), sep = "-")) %>%
  select(-Ekst, -Rzeka)


###################Ogarniecie danych pogodowych

Pogoda <- read.csv("D://Pulpit//Pogoda//Pogoda_Combo.csv")

Pogoda <- Pogoda |>
  mutate(DataKod = paste(Rok, str_pad(Mies, 2, pad = "0"), sep = "-"))

Pogoda <- Pogoda |>
  group_by(DataKod) |> 
  summarise(Rok = mean(Rok, na.rm=T),
            Mies = mean(Mies, na.rm=T),
            Sred_Temp = mean(Sred_Temp, na.rm=T),
            Abs_Temp_Max = max(Abs_Temp_Max, na.rm=T),
            Srd_Temp_Max = max(Srd_Temp_Max, na.rm=T),
            Abs_Temp_Min = min(Abs_Temp_Min, na.rm=T),
            Srd_Temp_Min = min(Sred_Temp_Min, na.rm=T),
            Min_Temp_Grunt = min(Min_Temp_Grunt, na.rm=T),
            Srd_Wiatr = mean(Wiatr, na.rm=T),
            Srd_Wilgot = mean(Sred_Wilgot, na.rm=T),
            Srd_Cisnienie_Pary = mean(Sred_Cisnienie_Pary, na.rm=T),
            Srd_Cisn = mean(Sred_Cisn, na.rm=T),
            Srd_Cisn_PzMorza = mean(Sred_Cisn_PoziomMorza, na.rm=T),
            Suma_Slonce = mean(Suma_Slonce, na.rm=T),
            Zachmurz = mean(Zachmurz, na.rm=T),
            Suma_Opad = mean(Suma_Opad, na.rm=T),
            Maks_Dob_Sum_Opad = max(Maks_Dob_Sum_Opad, na.rm=T),
            Suma_Opadu_Dzien = mean(Suma_Opadu_Dzien, na.rm=T),
            Suma_Opadu_Noc = mean(Suma_Opadu_Noc, na.rm=T),
            Maks_Pokryw_Snieg = mean(Maks_Pokryw_Snieg, na.rm=T),
            Dni_z_Snieg = mean(Dni_z_Snieg, na.rm=T),
            Dni_Z_Deszcz = mean(Dni_Z_Deszcz, na.rm=T),
            Dni_DeszczISnieg = mean(Dni_DeszczISnieg, na.rm=T),
            Dni_Grad = mean(Dni_Grad, na.rm=T),
            Dni_Mgla = mean(Dni_Mgla, na.rm=T),
            Dni_Zamglen = mean(Dni_Zamglen, na.rm=T),
            Dni_Sadz = mean(Dni_Sadz, na.rm=T),
            Dni_Gololedz = mean(Dni_Gololedz, na.rm=T),
            Dni_Zamiec_Niska = mean(Dni_Zamiec_Niska, na.rm=T),
            Dni_Zamiec_Wysoka = mean(Dni_Zamiec_Wysoka, na.rm=T),
            Dni_Zmetnienie = mean(Dni_Zmetnienie, na.rm=T),
            Dni_Wiatr = mean(Dni_Wiatr, na.rm=T),
            Dni_Big_Waitr = mean(Dni_Big_Waitr, na.rm=T),
            Dni_Burza = mean(Dni_Burza, na.rm=T),
            Dni_Rosa = mean(Dni_Rosa, na.rm=T),
            Dni_Szron = mean(Dni_Szron, na.rm=T))
```

# Faktyczna analiza

## P1 Jak wilgotność w pogodzie wpływa na jakość i ilość tymianku?

### H1 Stan wody w najbliższej mierzonej rzece nie ma zauważalnego wpływu na uprawę tymianku

### H2 Średnia wilgotność ma wpływ na wilgoć mierzoną w tymianku oraz na ilość olejków

### H3 Opady w miesiącach zbiorów tymianku negatywnie wpływają na jego jakość

### H4 Opady w miesiącach wzrostu tymianku pozytywnie wpływają na jego ilość 

## **P2 Jak sytuacja przy gruncie wpływa na jakość i ilość tymianku?**

### H1 Minimalna temperatura gruntu w pierwszych miesiącach wzrostu tymianku ma wpływ na jego ilość w okresie zbiorów.

### H2 Ilość dni z zaobserwowaną rosą w pierwszych miesiącach wzrostu tymianku ma wpływ na jego ilość w okresie zbiorów.

## **P3 Jak warunki atmosferyczne wpływają na jakość i ilość tymianku?**

### H1 Duże nasłonecznienie w miesiącach zbiorów tymianku pozytywnie wpływają na jego jakość.

### H2 Duże nasłonecznienie w miesiącach sadzenia tymianku negatywnie wpływają na jego ilość podczas zbiorów.

### H3 Ciśnienie atmosferyczne nie wpływa znacznie na uprawy tymianku.

### H4 Prędkość wiatru nie wpływa znacznie na uprawy tymianku.

okrojona bo nie znamy testow statystycznych i metod progrostycznych
do każdego pytania hipotezy jakas analiza z wizualizacja i zależnościami pokazanymi i wogole i tez mówimy nasza interpretacje tego
(wykres + interpretacja) (4 5 hipotez beng beng)
każdą omawiamy po krótce
niech te wykresy będą różnorodne z jakimiś roznymi danymi (kategoryzacja danych)

# Podsumowanie

przedstawiamy najważniejszy insight z tej analizy
puenta projektu jakas żeby można było zapamietac chociaż tyle
na bazie tego co zrobiliśmy co moznaby zrobić w przyszłości
